# Generated by Django 3.2.13 on 2022-06-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='house_id',
            field=models.CharField(blank=True, default='house_id', max_length=12),
        ),
    ]
