# Generated by Django 3.2.13 on 2022-06-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='house_id',
            field=models.CharField(blank=True, default='house_code', max_length=20),
        ),
    ]
