# Generated by Django 3.2.13 on 2022-06-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_house_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='house_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
